image: Visual Studio 2015
version: 5.4.{build}
build_script:
- ps: .\build.ps1 -Target "Default"
test: off
notifications:
- provider: Webhook
  url: https://webhooks.gitter.im/e/a15b32c76b5e78e1b355
  method: POST
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true